// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_HzF3kFxezYvY7x2O9SF9inF6r1w68rM',
    appId: '1:623474517754:web:865d2beb5a78355dca8b43',
    messagingSenderId: '623474517754',
    projectId: 'quick-bite-25b89',
    authDomain: 'quick-bite-25b89.firebaseapp.com',
    storageBucket: 'quick-bite-25b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2k-nN5uIFvOw8NaBHoVfWLA3BOEYvfuQ',
    appId: '1:623474517754:android:1185b532f6fe0349ca8b43',
    messagingSenderId: '623474517754',
    projectId: 'quick-bite-25b89',
    storageBucket: 'quick-bite-25b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB71p8FdYIKwYruihsChmP8xNre-80AeZg',
    appId: '1:623474517754:ios:50e4ceaa39cc8d77ca8b43',
    messagingSenderId: '623474517754',
    projectId: 'quick-bite-25b89',
    storageBucket: 'quick-bite-25b89.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB71p8FdYIKwYruihsChmP8xNre-80AeZg',
    appId: '1:623474517754:ios:50e4ceaa39cc8d77ca8b43',
    messagingSenderId: '623474517754',
    projectId: 'quick-bite-25b89',
    storageBucket: 'quick-bite-25b89.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_HzF3kFxezYvY7x2O9SF9inF6r1w68rM',
    appId: '1:623474517754:web:20ad82286eb32918ca8b43',
    messagingSenderId: '623474517754',
    projectId: 'quick-bite-25b89',
    authDomain: 'quick-bite-25b89.firebaseapp.com',
    storageBucket: 'quick-bite-25b89.firebasestorage.app',
  );
}
